#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2016 Intel Corporation.
#  All rights reserved.
#

SPDK_ROOT_DIR := $(CURDIR)/../../spdk

APP = trace_io_analysis

include $(SPDK_ROOT_DIR)/mk/nvme.libtest.mk
