#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2015 Intel Corporation.
#  All rights reserved.
#

SPDK_ROOT_DIR := $(CURDIR)/../../spdk

APP = trace_io_replay

include $(SPDK_ROOT_DIR)/mk/nvme.libtest.mk
